Add new options and SIGINT handling
art19/ecs-task-runner pull request #1
Opened 2017-12-30 04:49 UTC by johvet

2018-01-02 23:52 UTC, ziggythehamster requested changes

2018-01-02 23:52 UTC, ziggythehamster commented on index.js
> +        reason: 'User cancelled tasked'
I think this should be `User requested interrupt`

2018-01-02 23:52 UTC, ziggythehamster commented on lib/taskrunner.js
> +    let ecs = new AWS.ECS();
This could be a const

2018-01-02 23:52 UTC, ziggythehamster commented on lib/taskrunner.js
> +    let params = {
This could be a const

2018-01-02 23:52 UTC, ziggythehamster commented on index.js
> +      let params = {
This could be a const

2018-01-02 23:52 UTC, ziggythehamster commented on index.js
> +      let ecs = new AWS.ECS();
This could be a const.

2018-01-03 22:16 UTC, jcaffey approved these changes

2018-01-03 22:25 UTC, ziggythehamster approved these changes

2018-01-03 23:10 UTC, merged